ACCOUNT_BASE_URL = 'http://localhost:5000/v1/accounts'
EMAIL_TALEL = 'talel@talel.talel'
USERNAME_TALEL = 'taleldayekh'
EMAIL_BIANCA = 'bianca@bianca.bianca'
USERNAME_BIANCA = 'biancabasan'
PASSWORD = 'password'
