# Configure middleware for the Traefik API authentication
[http.middlewares.traefikApiAuth.basicAuth]
  users = ["HTPASSWD_USER_PASS"]

# Configure router for Traefik API to expose the built in
# "api@internal" service.
[http.routers.api]
  rule = "Host(`traefik.talel.io`)"
  entrypoints = ["websecure"]
  middlewares = ["traefikApiAuth"]
  service = "api@internal"

  [http.routers.api.tls]
    certResolver = "letsencrypt"
