"""Adding featured image field to article table

Revision ID: 3c8781323ae1
Revises: 5e7ad8ab720b
Create Date: 2022-03-29 17:44:30.758657

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3c8781323ae1'
down_revision = '5e7ad8ab720b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('featured_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'featured_image')
    # ### end Alembic commands ###
