"""Adding slug field to article table

Revision ID: 5e7ad8ab720b
Revises: f2f7257e520a
Create Date: 2022-02-17 15:37:51.748066

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5e7ad8ab720b'
down_revision = 'f2f7257e520a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'article', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    op.drop_column('article', 'slug')
    # ### end Alembic commands ###
