"""Adding meta_description and url fields

Revision ID: 69c04e8e4808
Revises: 3c8781323ae1
Create Date: 2022-05-16 14:41:57.709801

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '69c04e8e4808'
down_revision = '3c8781323ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'url')
    op.drop_column('article', 'meta_description')
    # ### end Alembic commands ###
