"""creating project table

Revision ID: 80712f5626d6
Revises: 99335da606ac
Create Date: 2021-08-24 15:25:55.064368

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '80712f5626d6'
down_revision = '99335da606ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('title', sa.String(), nullable=True), sa.Column('body', sa.Text(),
                                                                  nullable=True),
        sa.Column('html', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
