"""changes when downgrading sqlalchemy

Revision ID: 99335da606ac
Revises: c512fa75531e
Create Date: 2021-03-23 20:27:56.877059

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '99335da606ac'
down_revision = 'c512fa75531e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
