"""Add article table of contents column

Revision ID: ba7f12fb2236
Revises: 69c04e8e4808
Create Date: 2023-04-28 19:39:33.972876

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ba7f12fb2236'
down_revision = '69c04e8e4808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('table_of_contents', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'table_of_contents')
    # ### end Alembic commands ###
