name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types:
      - completed

jobs:
  hello_world:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Hello World Example
        run: echo "Hello World"

