name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    name: Quality Assurance
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

      redis:
        image: redis:6.2.4-alpine
        ports:
          - 6379:6379

    env:
      HOST: localhost
      SECRET_KEY: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Static Code Analysis
        run: |
          make lint
          make type-check

      - name: Unit Tests
        run: |
          make test-unit

      - name: E2E Tests
        run: |
          make test-e2e

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./unit-coverage.xml, ./e2e-coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
