name: CI

on: pull_request

jobs:
  qa:
    name: QA Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Lint
        run: make lint

      - name: Type check
        run: make type-check

      - name: Test
        run: make test-coverage

      - name: Upload test coverage
        uses: codecov/codecov-action@v1

