name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    name: Quality Assurance
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test
      DB_URI: postgresql://test:password@localhost:5432/test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      
      - name: Static Code Analysis
        run: |
          make lint
          make type-check

      - name: Unit Tests
        run: make test-unit

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1
